# Generated by Django 6.0 on 2025-12-19 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orderitem', '0002_alter_orderitem_price_at_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='product',
            new_name='product_id',
        ),
    ]
