# Generated by Django 6.0 on 2025-12-18 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderitem', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='price_at_time',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity_kg',
            field=models.PositiveIntegerField(),
        ),
    ]
