# Generated by Django 6.0 on 2025-12-22 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderitem', '0003_rename_product_orderitem_product_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('Pending', 'PENDING'), ('Confirmed', 'CONFIRMED'), ('Deliverd', 'DELIVERED')], default='Pending', max_length=20),
        ),
    ]
